### ISSUE TITLE
Still in beta?

### ISSUE THREAD

**Issue by tvvocold** [symbiose/symbiose#474]
i got this after i put the files in php5.4 env.

Loading default interface
Retrieving booter
Webos.Error: An error occurred while loading a request group (no working transport found)
at api calling action "getContents" in module "file" with arguments {"file":"/usr/lib/gitfs/webos.js"}

PS:i use openshift.

**Comment by tvvocold** [comment]
Never mind. i checked https://github.com/symbiose/symbiose/issues/432 and  mv .htaccess .npmignore .travis.yml to www-root and get it run.

**Comment by tvvocold** [comment]
but when release (not beta)?

**Comment by andersevenrud** [comment]
@tvvocold Judging by the [Milestones](https://github.com/symbiose/symbiose/milestones) there is no planned stable-release.

**Comment by emersion** [comment]
Hi,

The stable release is planned (see _1.0_), but there's much to do before that.

Anyway, I think it would be a good idea to stop implementing new features for now, fix bugs and release a stable version. What do you think?

**Comment by tvvocold** [comment]
That would be nice!

**Comment by emersion** [comment]
All right, just reorganized milestones. All known bugs are in [1.0](https://github.com/symbiose/symbiose/milestones/1.0). As soon as they get closed, I'll release the first stable version. ;-)

**Comment by Maastodonte** [comment]
:+1: 
Love it !
