### ISSUE TITLE
Nice job!

### ISSUE THREAD

**Issue by tvvocold** [symbiose/symbiose#477]
BTW, May i ask a fundamental question?
Why php? (not Java)

**Comment by emersion** [comment]
Haha, Java. You're jocking, right? :-)

No, seriously, PHP is installed on most servers so it's easy to setup. But now I think it would be better to use Node.js.

**Comment by tvvocold** [comment]
but the node.js' or php' performance is lower than java, right?

**Comment by emersion** [comment]
First performance test found: http://blog.shinetech.com/2013/10/22/performance-comparison-between-node-js-and-java-ee/

To be honest: I don't like Java. But this is a personal opinion. ;-)

**Comment by tvvocold** [comment]
Plz look at the comment...

**Comment by emersion** [comment]
Which one?

**Comment by tvvocold** [comment]
http://blog.shinetech.com/2013/10/22/performance-comparison-between-node-js-and-java-ee/#comment-5265

**Comment by tvvocold** [comment]
i think it would be nicer to use php as frontend and golang as backend.

**Comment by emersion** [comment]
WTF. PHP as frontend?

**Comment by emersion** [comment]
Anyway, I linked this test just to say that performance is not an issue.

**Comment by emersion** [comment]
(E.g. Paypal recently migrated from java to Node)

**Comment by eemi2010** [comment]
Our desktop is based on Java (UI + Backend) and it s not that bad I d say :)
