### ISSUE TITLE
webos error 

### ISSUE THREAD

**Issue by daliMejri** [symbiose/symbiose#502]
after deployment of webos on local server ubuntu12.04 server apache2 i have this problem 
Loading default interface
Retrieving booter
Webos.Error: An error occurred while loading a request (no working transport found)
at api calling action "loadBooter" in module "userInterface" with arguments "%7B%22ui%22%3Afalse%7D"

Webos.Error: An error occurred while loading a request group (no working transport found)
at api calling action "getContents" in module "file" with arguments {"file":"/usr/lib/gitfs/webos.js"}

Webos.Error: An error occurred while loading a request group (no working transport found)
at api calling action "getContents" in module "file" with arguments {"file":"/usr/lib/webos/fstab.js"}

Webos.Error: An error occurred while loading a request group (no working transport found)
at api calling action "getLanguage" in module "translation" with arguments {}

**Comment by emersion** [comment]
Are you sure you enabled `.htaccess` files? Can you check you server logs?

**Comment by daliMejri** [comment]
houw i can enabled .htaccess files

**Comment by daliMejri** [comment]
i verified error.log of apache server 
[Wed May 27 05:00:04 2015] [error] [client 127.0.0.1] File does not exist: /var/www/symbiose/build/api, referer: http://localhost/symbiose/build/index.php

**Comment by emersion** [comment]
You'll have to enable `.htaccess` files and motrewrite in order to get Symbiose working.

For `.htaccess` files, add the `AllowOverride All` directive to your apache config.

**Comment by daliMejri** [comment]
it's work thank you
