### ISSUE TITLE
connect to data base 

### ISSUE THREAD

**Issue by daliMejri** [symbiose/symbiose#505]
I deployed symbiose in my local server. when i trie create a new user ther is problem with data base .

Webos.Error: Registration failed
Cannot find captcha with id #0. Your session might be outdated, please try again

**Comment by daliMejri** [comment]
Webos.Error: Registration failed
Malformed JSON data (SyntaxError): JSON.parse: unexpected character. Data :

Fatal error: Call to a member function get() on a non-object in /var/www/symbiose/build/lib/ctrl/api/UserController.class.php on line 634

    at api calling action "register" in module "user"
    with arguments "%7B%22data%22%3A%7B%22username%22%3A%22ali%22%2C%22realname%22%3A%22ali%22%2C%22password%22%3A%22dali1920%22%2C%22email%22%3A%22mohamedali.mejri%40esprit.tn%22%7D%2C%22captchaData%22%3A%7B%22id%22%3A0%2C%22value%22%3A%2257209%22%7D%7D"

**Comment by daliMejri** [comment]
i have the same problem after update UserController.class.php

Webos.Error: Registration failed
Malformed JSON data (SyntaxError): JSON.parse: unexpected character. Data :

Fatal error: Call to a member function load() on a non-object in /var/www/symbiose/build/lib/ctrl/api/UserController.class.php on line 612

    at api calling action "register" in module "user"
    with arguments "%7B%22data%22%3A%7B%22username%22%3A%22test%22%2C%22realname%22%3A%22test%22%2C%22password%22%3A%22aliali%22%2C%22email%22%3A%22test%40yahoo.fr%22%7D%2C%22captchaData%22%3A%7B%22id%22%3A0%2C%22value%22%3A%2285130%22%7D%7D"

**Comment by emersion** [comment]
Ow, sorry, just fixed it ;-)

**Comment by daliMejri** [comment]
can i change login from database to domain user from ActiveDirectory  in windows server 2012 R2

**Comment by emersion** [comment]
No, but LDAP login is available. See the wiki for more information about this. I guess you could create an ActiveDirectory login script from the LDAP one, if a php ActiveDirectory library exists.

**Comment by daliMejri** [comment]
ok Thank you i will try it
