### ISSUE TITLE
LDAP authentication failed

### ISSUE THREAD

**Issue by daliMejri** [symbiose/symbiose#511]
i trie to change register and authentification with ldap but i have this problem.

Loading default interface
Retrieving booter
Webos.Error: Cannot connect to LDAP server "localhost" on port 389 as "cn=Manager,dc=example,dc=org"

Inserting structure
Applying stylesheets
Initialising interface
Running .//usr/lib/webos/config.js
Running .//usr/lib/webos/theme.js
Running .//usr/lib/nautilus/widgets.js
Running .//usr/lib/webos/applications.js
Running .//usr/lib/webos/icons.js
Running .//usr/lib/webos/jquery.transit.min.js
Running .//usr/lib/webos/fullscreen.js
Running .//usr/lib/webos/jquery.mousewheel.js
Running .//usr/lib/webos/clipboard.js
Running .//usr/lib/gtk/widgets.js
Running .//usr/lib/compiz/widgets.js
Running .//usr/lib/compiz/workspaces.js
Running .//usr/lib/compiz/reviver.js
Running .//usr/lib/gnome/widgets.js
Running .//usr/lib/gnome/jquery.scrollto.js
Running .//usr/lib/elementary/menus.js
Running .//usr/lib/elementary/notifications.js
Running .//usr/lib/gnome/power.js
Running .//usr/lib/nautilus/nautilus.js
Running .//usr/lib/gnome-screensaver/webos.js
Running .//usr/lib/xtag/webos.js
Running .//usr/lib/elementary/main.js
Running .//boot/uis/elementary/index.js
Initialising interface

**Comment by emersion** [comment]
Try:
```bash
nmap 127.0.0.1
telnet 17.0.0.1 389
```

**Comment by daliMejri** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/7644255/8688535/37b27216-2a95-11e5-9b0b-cebc367de1cc.png)

**Comment by emersion** [comment]
Your LDAP server doesn't seem to be up and running.

**Comment by daliMejri** [comment]
how can i enabel and run it i just fellow the tuto step by step
