### ISSUE TITLE
LDAP server failed

### ISSUE THREAD

**Issue by daliMejri** [symbiose/symbiose#514]
I have install ldap server on ubuntu server and he work 100%.
when i atteched him to symbiose project . i get this
![screenshot from 2015-07-26 10 53 55](https://cloud.githubusercontent.com/assets/7644255/8895156/cf1d136e-33c7-11e5-9643-b5c0bcad8232.png)

**Comment by daliMejri** [comment]
this ldap serverhome page

![screenshot from 2015-07-26 10 55 42](https://cloud.githubusercontent.com/assets/7644255/8895164/f8014d22-33c7-11e5-8b05-187f3d9931cc.png)

**Comment by emersion** [comment]
Can you open your browser console (press `F12`) and paste here the logs please?

**Comment by daliMejri** [comment]
boot.min.js:7 Loading from network: /usr/lib/webos/fstab.js
boot.min.js:7   Loaded: /usr/lib/webos/config.js
boot.min.js:7   Loading from cache: /usr/lib/webos/config.js
boot.min.js:7 Not re-executing script: /usr/lib/webos/config.js
boot.min.js:7   Loaded: /usr/lib/webos/config.js
boot.min.js:7   Loaded: /usr/lib/webos/theme.js
boot.min.js:7 Loading from network: /usr/lib/jquery.filedrop.js
boot.min.js:7 Loading from network: /usr/lib/fileuploader.js
boot.min.js:7 Loading from network: /usr/lib/webos/applications.js
boot.min.js:7 Loading from network: /usr/lib/webos/data.js
boot.min.js:7   Loaded: /usr/lib/webos/applications.js
boot.min.js:7   Loading from cache: /usr/lib/webos/theme.js
boot.min.js:7 Not re-executing script: /usr/lib/webos/theme.js
boot.min.js:7   Loaded: /usr/lib/webos/theme.js
boot.min.js:7   Loaded: /usr/lib/webos/icons.js
boot.min.js:7   Loaded: /usr/lib/webos/jquery.transit.min.js
boot.min.js:7   Loaded: /usr/lib/webos/fullscreen.js
boot.min.js:7   Loaded: /usr/lib/webos/jquery.mousewheel.js
boot.min.js:7   Loaded: /usr/lib/webos/clipboard.js
boot.min.js:7 Loading from network: /usr/share/css/gtk/widgets.css
boot.min.js:7   Loaded: /usr/lib/compiz/widgets.js
boot.min.js:7   Loaded: /usr/lib/compiz/workspaces.js
boot.min.js:7   Loaded: /usr/lib/compiz/reviver.js
boot.min.js:7   Loaded: /usr/lib/gnome/widgets.js
boot.min.js:7   Loaded: /usr/lib/gnome/jquery.scrollto.js
boot.min.js:7   Loaded: /usr/lib/elementary/menus.js
boot.min.js:7   Loaded: /usr/lib/elementary/notifications.js
boot.min.js:7   Loaded: /usr/lib/gnome/power.js
boot.min.js:7 Loading from network: /usr/share/css/nautilus/main.css
boot.min.js:7 Loading from network: /usr/share/css/nautilus/window.css
boot.min.js:7 Loading from network: /usr/lib/nautilus/widgets.js
boot.min.js:7 Loading from network: /usr/lib/jquery.filedrop.js
boot.min.js:7 Loading from network: /usr/lib/fileuploader.js
boot.min.js:7   Loading from cache: /usr/lib/webos/applications.js
boot.min.js:7 Not re-executing script: /usr/lib/webos/applications.js
boot.min.js:7   Loaded: /usr/lib/webos/applications.js
boot.min.js:7 Loading from network: /usr/share/css/gnome-screensaver/main.css
boot.min.js:7 Loading from network: /usr/lib/xtag/core.min.js
boot.min.js:7   Loading from cache: /usr/lib/webos/applications.js
boot.min.js:7 Not re-executing script: /usr/lib/webos/applications.js
boot.min.js:7   Loaded: /usr/lib/webos/applications.js
boot.min.js:7   Loaded: /usr/lib/elementary/main.js
boot.min.js:7 Loading from network: /usr/lib/gnome/ini.js
boot.min.js:7   Loading from cache: /usr/lib/webos/theme.js
boot.min.js:7 Not re-executing script: /usr/lib/webos/theme.js
boot.min.js:7   Loaded: /usr/lib/webos/theme.js

**Comment by emersion** [comment]
What if you skip the build step?

**Comment by daliMejri** [comment]
no idont skip the build step in the first image this is th url in may server 192.168.241.128/symbiose/build/index.php
